[package]
name = "gdiplus2-sys"
version = "0.1.0"
edition = "2021"

[dependencies]
winapi = { version = "0.3", features = [
    "commctrl",
    "vcruntime",
    "windef",
    "wingdi",
    "wtypes"
]}

#[build-dependencies]
#bindgen = "0.59"